import streamlit as st
import pandas as pd
import plotly.express as px

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="Eco-Stats", layout="wide")

st.title("🌿 Eco-Stats Dashboard")
st.markdown("""
Upload the CSV file generated by **EcoField Logger** to visualize biodiversity 
and compare habitats.
""")

# --- HELPER FUNCTION: CALCULATE SIMPSON'S INDEX ---
def calculate_simpsons_index(df):
    """
    Simpson's Index (D) measures diversity. 
    0 = No diversity (only 1 species found).
    1 = Infinite diversity.
    """
    N = df['count'].sum() # Total organisms
    if N < 2:
        return 0
    
    # Sum of n(n-1)
    numerator = sum(n * (n - 1) for n in df['count'])
    D = 1 - (numerator / (N * (N - 1)))
    return round(D, 3)

# --- FILE UPLOADER ---
uploaded_file = st.file_uploader("Upload Group Data (CSV)", type=['csv'])

if uploaded_file is not None:
    try:
        # Load data
        df = pd.read_csv(uploaded_file)
        
        # --- DATA CLEANING ---
        # Ensure column names match your HTML form names exactly
        # If your CSV headers are capitalized, we normalize them here
        df.columns = [c.lower().strip() for c in df.columns]
        
        # Check if required columns exist
        required_cols = ['species', 'count', 'habitat']
        if not all(col in df.columns for col in required_cols):
            st.error(f"CSV must contain columns: {required_cols}")
        else:
            # --- DASHBOARD METRICS ---
            st.divider()
            col1, col2, col3 = st.columns(3)
            
            total_obs = df['count'].sum()
            unique_species = df['species'].nunique()
            top_habitat = df.groupby('habitat')['count'].sum().idxmax()
            
            col1.metric("Total Organisms Observed", total_obs)
            col2.metric("Species Richness", unique_species)
            col3.metric("Most Populated Habitat", top_habitat.title())
            
            st.divider()

            # --- VISUALIZATION ROW 1 ---
            c1, c2 = st.columns(2)
            
            with c1:
                st.subheader("Habitat Composition")
                # Bar chart: Total count per habitat
                habitat_counts = df.groupby('habitat')['count'].sum().reset_index()
                fig_hab = px.bar(habitat_counts, x='habitat', y='count', 
                                 color='habitat', title="Total Organisms by Habitat")
                st.plotly_chart(fig_hab, use_container_width=True)
                
            with c2:
                st.subheader("Species Abundance")
                # Pie chart: Which species are most common?
                fig_pie = px.pie(df, values='count', names='species', 
                                 title="Species Distribution (Overall)")
                st.plotly_chart(fig_pie, use_container_width=True)

            # --- VISUALIZATION ROW 2: DIVERSITY ---
            st.subheader("Biodiversity Analysis (Simpson's Index)")
            st.info("Simpson's Index ranges from 0 (Low Diversity) to 1 (High Diversity).")
            
            # Calculate Diversity PER Habitat
            habitats = df['habitat'].unique()
            diversity_data = []
            
            for h in habitats:
                sub_df = df[df['habitat'] == h]
                d_index = calculate_simpsons_index(sub_df)
                diversity_data.append({'Habitat': h, 'Diversity Index': d_index})
            
            div_df = pd.DataFrame(diversity_data)
            
            fig_div = px.bar(div_df, x='Habitat', y='Diversity Index', 
                             color='Diversity Index', 
                             range_y=[0, 1],
                             color_continuous_scale='Viridis')
            st.plotly_chart(fig_div, use_container_width=True)

            # --- RAW DATA VIEW ---
            with st.expander("View Raw Data"):
                st.dataframe(df)

    except Exception as e:
        st.error(f"Error reading file: {e}")

else:
    st.info("Waiting for CSV file upload...")
    
